from canvasapi import Canvas
from config import Config

canvas = Canvas(Config.CANVAS_API_URL, Config.CANVAS_API_KEY)

def create_canvas_quiz(course_id, questions):
    # Obtener el curso
    course = canvas.get_course(course_id)
    
    quiz_params = {
        'title': 'Generated Quiz 1',
        'description': 'A quiz generated by AI.',
        'quiz_type': 'assignment',
        'published': True,
        'question_types':['multiple_choice']
    }
    
    # Crea el quiz en el curso
    quiz = course.create_quiz(quiz_params)

    # print(questions)

    # Añadir las preguntas al quiz
    for question in questions:
        question_params = {
            'question_name': "Texto de prueba",
            'question_text': question['question_text'],
            'question_type': 'multiple_choice_question',
            'points_possible': 1,
            'answers': []
        }
        
        # print(question['question_text'])
        # Crea la lista de respuestas
        for answer in question['answers']:
            answer_data = {
                'text': answer['answer_text'],
                'weight': 100 if answer['correct'] else 0
            }
            
            # print(answer['answer_text'])
            
            question_params['answers'].append(answer_data)
            # question_params['question']['answers'].append(answer_data)

        # print(f"Question Params: {question_params}")
        
        # print(question_params)
        # print("----------------")
        # Agrega la pregunta al quiz
        # quiz.create_question(**question_params)
        quiz.create_question(question=question_params)
        # quiz.create_question(question_params)

    return quiz.id
    # return question_params